# Uninstall Nginx (to debug)
# ansible-playbook uninstnginx.yml
- name: Play - Uninstall Nginx
  hosts: localhost
  become: yes
  tasks: 
    - name: Unnstall Nginx
      apt: name=nginx state=absent

# Type $ ansible-playbook uninstnginx.yml && sudo apt purge nginx nginx-common nginx-full -y && docker-compose up -d && ansible-playbook hello.yml
# After execution